# Generated by Django 3.2.5 on 2021-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petal_length', models.FloatField()),
                ('petal_width', models.FloatField()),
                ('sepal_length', models.FloatField()),
                ('sepal_width', models.FloatField()),
            ],
        ),
    ]
