# Generated by Django 3.1.5 on 2021-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomForest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gest', models.IntegerField()),
                ('birthweight', models.FloatField()),
                ('MAS', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('multip', models.BooleanField()),
                ('level_3', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='iris',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
